---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: installer
  namespace: sysdigcloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: installer
subjects:
- kind: ServiceAccount
  name: installer
  namespace: sysdigcloud
