apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sysdig-agent
resources:
- namespace.yaml
- clusterrole.yaml
- rolebinding.yaml
- serviceaccount.yaml
- configmap.yaml
- daemonset-v2.yaml
