apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: sysdig-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sysdig-agent
subjects:
  - kind: ServiceAccount
    name: sysdig-agent
