############################ DEPRECATION NOTICE ##########################
# This daemonset yaml configures everything as an environment variable.
# We recommend to use v2 daemonset which instead leverages Kubernetes
# best practices like Secrets and ConfigMaps
##########################################################################
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: sysdig-agent
  labels:
    app: sysdig-agent
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sysdig-agent
    spec:
      volumes:
      - name: modprobe-d
        hostPath:
          path: /etc/modprobe.d
      - name: dshm
        emptyDir:
          medium: Memory
      - name: dev-vol
        hostPath:
          path: /dev
      - name: proc-vol
        hostPath:
          path: /proc
      - name: boot-vol
        hostPath:
          path: /boot
      - name: modules-vol
        hostPath:
          path: /lib/modules
      - name: usr-vol
        hostPath:
          path: /usr
      - name: run-vol
        hostPath:
          path: /run
      - name: varrun-vol
        hostPath:
          path: /var/run
      hostNetwork: true
      hostPID: true
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      ### OPTIONAL: If using OpenShift or Kubernetes RBAC you need to uncomment the following line
      # serviceAccount: sysdig-agent
      terminationGracePeriodSeconds: 5
      initContainers:
      - name: sysdig-agent-kmodule
        image: sysdig/agent-kmodule
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          # Resources needed are subjective on the actual workload
          # please refer to Sysdig Support for more info about it
          requests:
            cpu: 1
            memory: 384Mi
          limits:
            memory: 512Mi
        volumeMounts:
        - mountPath: /host/boot
          name: boot-vol
          readOnly: true
        - mountPath: /host/lib/modules
          name: modules-vol
          readOnly: true
        - mountPath: /etc/modprobe.d
          name: modprobe-d
          readOnly: true
        - mountPath: /host/usr
          name: usr-vol
          readOnly: true
      containers:
      - name: sysdig-agent
        image: sysdig/agent-slim
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          # Resources needed are subjective on the actual workload
          # please refer to Sysdig Support for more info about it
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 1024Mi
        readinessProbe:
          exec:
            command: [ "test", "-e", "/opt/draios/logs/running" ]
          initialDelaySeconds: 10
        env:
        ### REQUIRED: replace with your Sysdig Platform access key
        - name: ACCESS_KEY
          value: key
        ### OPTIONAL: add tags for this host
        # - name: TAGS
        #   value: linux:ubuntu,dept:dev,local:nyc
        ### OPTIONAL: Needed to connect to a Sysdig On-Premises backend
        # - name: COLLECTOR_PORT
        #   value: "6443"
        # - name: COLLECTOR
        #   value: 192.168.1.200
        # - name: SECURE
        #   value: "true"
        # - name: CHECK_CERTIFICATE
        #   value: "false"
        ### OPTIONAL: Add additional parameters to the agent, refer to our Docs to know all options available
        # - name: ADDITIONAL_CONF
        #   value: |
        #     new_k8s: true
        #     k8s_cluster_name: production
        volumeMounts:
        - mountPath: /host/dev
          name: dev-vol
          readOnly: false
        - mountPath: /host/proc
          name: proc-vol
          readOnly: true
        - mountPath: /host/run
          name: run-vol
        - mountPath: /host/var/run
          name: varrun-vol
        - mountPath: /dev/shm
          name: dshm
