apiVersion: v1
kind: ServiceAccount
metadata:
  name: sysdig-agent
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: sysdig-agent
rules:
- apiGroups:
  - "extensions"
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - replicationcontrollers
  - services
  - events
  - ingresses
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /healthz
  - /healthz/*
  verbs:
  - get

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: sysdig-agent
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: sysdig-agent
roleRef:
  kind: ClusterRole
  name: sysdig-agent
  apiGroup: rbac.authorization.k8s.io
