---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: installer-readony
  namespace: sysdigcloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: installer-readonly
subjects:
- kind: ServiceAccount
  name: installer-readonly
  namespace: sysdigcloud
