global:
  admin:
    username: <a-valid-email-address>
  dnsName: <change-me>
  ingressClassName: haproxy
  ingressNetworking: hostnetwork
  license: <change-me>
  quaypullsecret: <change-me>
  storageClassProvisioner: aws
schema_version: 1.0.0
size: medium
sysdigCommonConfig:
  size: medium
